// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVNhhR4qOIqABn81E0SZj3HzvY48BPXQ',
    appId: '1:355447639535:android:7939baabcb8af145093a1a',
    messagingSenderId: '355447639535',
    projectId: 'pickuppal-e569d',
    storageBucket: 'pickuppal-e569d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Lk2EZclslsOWI3v206apKMz8hs8nneo',
    appId: '1:355447639535:ios:af05e70c13b89573093a1a',
    messagingSenderId: '355447639535',
    projectId: 'pickuppal-e569d',
    storageBucket: 'pickuppal-e569d.firebasestorage.app',
    iosBundleId: 'com.example.pickUpPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Lk2EZclslsOWI3v206apKMz8hs8nneo',
    appId: '1:355447639535:ios:af05e70c13b89573093a1a',
    messagingSenderId: '355447639535',
    projectId: 'pickuppal-e569d',
    storageBucket: 'pickuppal-e569d.firebasestorage.app',
    iosBundleId: 'com.example.pickUpPal',
  );
}
